
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/url-shortener

hooks:
  BeforeInstall:
    - location: move_old_pkg.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: ec2-user