version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn package
artifacts:
  files:
    - scripts/*
    - target/url-shortener-in-aws-1.1-SNAPSHOT.jar
    - appspec.yml